title: School AI Blog 🤖
description: Learn AI, coding and technology easily

theme: minima

baseurl: "/SchoolAI.github.io"   # 👈 ye add karo


header_pages:
  - index.md
  - about.md
  - contact.md

minima:
  skin: dark
